// Single import point for every model. Lets services do
//   const { Customer, Sale, ... } = require('../../models');
module.exports = {
  User: require('./User'),
  Society: require('./Society'),
  SocietyPhase: require('./SocietyPhase'),
  ExpenseCategory: require('./ExpenseCategory'),
  Partner: require('./Partner'),
  PartnerLedgerEntry: require('./PartnerLedgerEntry'),
  Inventory: require('./Inventory'),
  Purchase: require('./Purchase'),
  PurchasePaymentEntry: require('./PurchasePaymentEntry'),
  Sale: require('./Sale'),
  SalePaymentEntry: require('./SalePaymentEntry'),
  Vendor: require('./Vendor'),
  ExpenseBill: require('./ExpenseBill'),
  ExpensePayment: require('./ExpensePayment'),
  CommissionBill: require('./CommissionBill'),
  CommissionPayment: require('./CommissionPayment'),
  ResaleDeal: require('./ResaleDeal'),
  ResaleBuyerPayment: require('./ResaleBuyerPayment'),
  ResaleSellerPayout: require('./ResaleSellerPayout'),
  InventoryOwnershipHistory: require('./InventoryOwnershipHistory'),
  VendorType: require('./VendorType'),
  Customer: require('./Customer'),
  CustomerPayment: require('./CustomerPayment'),
  PaymentAllocation: require('./PaymentAllocation'),
  Account: require('./Account'),
  AccountOpeningBalance: require('./AccountOpeningBalance'),
  Transaction: require('./Transaction'),
  Party: require('./Party'),
  Loan: require('./Loan'),
  LoanRepayment: require('./LoanRepayment'),
  AuditLog: require('./AuditLog'),
};
